site_name: DnD Chronicles Manager
site_description: Tools for DMs to create branching storylines and manage characters.
site_url: https://DennisLent.github.io/dnd-chronicles-manager/
repo_url: https://github.com/DennisLent/dnd-chronicles-manager
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
nav:
  - Home: index.md
  - Character Creator: releases.md
  - Development: development.md
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DennisLent/dnd-chronicles-manager
