name: Build & Release (Tauri)

on:
  push:
    branches: [main]          # build on main pushes
    tags: ['v*']              # release on tags
  pull_request:
    branches: [main]          # build on PRs to main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: apps/character-creator

    steps:
      - uses: actions/checkout@v4

      # Install Node (no package-manager cache here)
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install pnpm, add to PATH
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # Install deps for the app dir
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Rust toolchain
      - uses: dtolnay/rust-toolchain@stable

      # Linux runtime deps for Tauri bundling
      - name: Install Linux deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev libwebkit2gtk-4.1-dev \
            libappindicator3-dev librsvg2-dev patchelf \
            libfuse2 desktop-file-utils

      # Build (AppImage needs extract-and-run on CI; harmless on other OSes)
      - name: Build Tauri bundle
        run: pnpm tauri build
        env:
          CI: true
          APPIMAGE_EXTRACT_AND_RUN: 1

      - name: Upload bundle artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-bundles
          path: apps/character-creator/src-tauri/target/release/bundle/**

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
          draft: false
          prerelease: false
