name: Build & Release (Tauri)

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: apps/character-creator

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: dtolnay/rust-toolchain@stable

      - name: Install Linux deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev libwebkit2gtk-4.1-dev \
            libappindicator3-dev librsvg2-dev patchelf \
            libfuse2 desktop-file-utils

      - name: Typecheck
        run: pnpm run typecheck

      - name: Debug TS config (paths)
        if: failure() && runner.os == 'Linux'
        run: |
          echo "Showing tsconfig.app.json compilerOptions.paths (raw lines)"
          sed -n '/"paths"/,+6p' tsconfig.app.json || true
          echo "tsc --showConfig excerpt:"
          pnpm exec tsc --showConfig -p tsconfig.app.json | sed -n '1,160p'
          echo "List src/lib"
          ls -la src/lib || true

      - name: Build Tauri bundle
        run: pnpm tauri build
        env:
          CI: true
          APPIMAGE_EXTRACT_AND_RUN: 1

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-bundles
          path: apps/character-creator/src-tauri/target/release/bundle/**
          if-no-files-found: error

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
          draft: false
          prerelease: false
